#!/bin/sh
perl -i -p0e 's/<!-- START.*END -->\n*/`cat reference_links`/se' *.md
perl -i -p0e 's/<!-- START.*END -->\n*/`cat reference_links`/se' */*.md
perl -i -p0e 's/<!-- START.*END -->\n*/`cat reference_links`/se' */*/*.md
