name: Publish Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

permissions:
  contents: write

concurrency:
  group: deploy-docs
  cancel-in-progress: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Deploy docs
        run: |
          cd docs
          mkdocs gh-deploy --force
