name: "Publish candidate/release to NetflixOSS and Maven Central"
on:
  push:
    tags:
      - v*.*.*
      - v*.*.*-rc.*
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git
        run: |
          git config --global user.name "Mantis OSS Maintainers"
          git config --global user.email "mantis-oss-dev@googlegroups.com"
      - uses: actions/checkout@v2
      - name: Setup jdk
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Publish candidate
        if: contains(github.ref, '-rc.')
        uses: gradle/gradle-build-action@v2
        env:
          NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
          NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
          NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
          NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
        with:
          arguments: -Prelease.useLastTag=true -x test candidate
      - name: Publish release
        if: (!contains(github.ref, '-rc.'))
        uses: gradle/gradle-build-action@v2
        env:
          NETFLIX_OSS_SONATYPE_USERNAME: ${{ secrets.ORG_SONATYPE_USERNAME }}
          NETFLIX_OSS_SONATYPE_PASSWORD: ${{ secrets.ORG_SONATYPE_PASSWORD }}
          NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
          NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
          NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
          NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
          NETFLIX_OSS_SONATYPE_STAGING_PROFILE_ID: "c3547130240327"
        with:
          arguments: -Prelease.useLastTag=true -x test final
